name: 'my_new_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:
  - "target"
  - "dbt_packages"

models:
  my_new_project:
    staging:
      +materialized: view
      european_soccer:
        +schema: staging_european_soccer
        stg_players:
          +materialized: view # Ensuring stg_players is materialized as a view
    marts:
      +materialized: table
      european_soccer:
        +schema: mart_european_soccer
