SELECT
  team_api_id AS team_id,
  PARSE_DATE('%Y-%m-%d', SUBSTR(CAST(date AS STRING),0,10)) AS team_attribute_date,
  buildUpPlaySpeed,
  buildUpPlaySpeedClass,
  buildUpPlayDribbling,
  buildUpPlayDribblingClass,
  buildUpPlayPassing,
  buildUpPlayPassingClass,
  buildUpPlayPositioningClass,
  chanceCreationPassing,
  chanceCreationPassingClass,
  chanceCreationCrossing,
  chanceCreationCrossingClass,
  chanceCreationShooting,
  chanceCreationShootingClass,
  chanceCreationPositioningClass,
  defencePressure,
  defencePressureClass,
  defenceAggression,
  defenceAggressionClass,
  defenceTeamWidth,
  defenceTeamWidthClass,
  defenceDefenderLineClass
FROM {{ source('European_Soccer', 'Team_Attributes') }}